name: Trigger ECS Task via SQS on QA PR

on:
  pull_request:
    branches:
      - qa

jobs:
  send-sqs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Send message to SQS
        run: |
          aws sqs send-message \
            --queue-url https://sqs.ap-south-1.amazonaws.com/546149929942/qa-test-trigger-queue \
            --message-body "Trigger ECS task for PR #${{ github.event.pull_request.number }}"
